-- ----------------------------
-- 2023.12.25工作流关系表加5个通用字段
-- ----------------------------
ALTER TABLE `ACT_EXT_RELATION`
    ADD COLUMN `DELETE_FLAG` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '删除标志' AFTER `EXT_JSON`,
ADD COLUMN `CREATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '创建时间' AFTER `DELETE_FLAG`,
ADD COLUMN `CREATE_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建用户' AFTER `CREATE_TIME`,
ADD COLUMN `UPDATE_TIME` datetime(0) NULL DEFAULT NULL COMMENT '修改时间' AFTER `CREATE_USER`,
ADD COLUMN `UPDATE_USER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '修改用户' AFTER `UPDATE_TIME`;